---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For having the full context, this file should be read
# with the openstack-helm-infra repository, where nodesets
# and jobs are defined.
# NOTE(evrardjp): Some jobs and playbooks haven't been
# migrated to openstack-helm-infra yet.
- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-helm-lint
        - openstack-helm-bandit
        - openstack-helm-cinder-train-ubuntu_bionic
        - openstack-helm-cinder-ussuri-ubuntu_bionic
        - openstack-helm-compute-kit-train-ubuntu_bionic
        - openstack-helm-compute-kit-ussuri-ubuntu_bionic
        - openstack-helm-horizon-train-ubuntu_bionic
    gate:
      jobs:
        - openstack-helm-lint
        - openstack-helm-tls:
            # NOTE(aostapenko) While keeping this job non-voting in gate
            # pipeline may not seem to have sense - disabling it is temporary
            # and job result should be kept visible so it's not forgotten
            # to be enabled first thing after ubuntu-bionic-expanded nodes
            # are available
            voting: false
        - openstack-helm-cinder-train-ubuntu_bionic
        - openstack-helm-compute-kit-train-ubuntu_bionic
        - openstack-helm-horizon-train-ubuntu_bionic
        - openstack-helm-multinode-compute-kit-train-ubuntu_bionic
        - openstack-helm-multinode-cinder-train-ubuntu_bionic
    post:
      jobs:
        - publish-openstack-helm-charts
    periodic:
      jobs:
        - openstack-helm-keystone-ldap
        - openstack-helm-cinder-ocata-ubuntu_xenial
        - openstack-helm-cinder-pike-ubuntu_xenial
        - openstack-helm-cinder-queens-ubuntu_xenial
        - openstack-helm-cinder-rocky-ubuntu_bionic
        - openstack-helm-cinder-stein-ubuntu_bionic
        - openstack-helm-compute-kit-ocata-ubuntu_xenial
        - openstack-helm-compute-kit-pike-ubuntu_xenial
        - openstack-helm-compute-kit-queens-ubuntu_xenial
        - openstack-helm-compute-kit-rocky-ubuntu_bionic
        - openstack-helm-compute-kit-stein-ubuntu_bionic
        - openstack-helm-tungsten-fabric-train
        - openstack-helm-tungsten-fabric-ussuri
    experimental:
      jobs:
        - openstack-helm-apparmor
        - openstack-helm-tls
        - openstack-helm-apparmor-cinder
        - openstack-helm-netpol-compute-kit
        - openstack-helm-netpol-compute-kit-train
        - openstack-helm-netpol-compute-kit-ussuri
        - openstack-helm-netpol-cinder
        - openstack-helm-multinode-compute-kit-train-ubuntu_bionic
        - openstack-helm-multinode-cinder-train-ubuntu_bionic
        # NOTE(srwilkers): Disabling the following jobs until
        # issues with the kubeadm-aio based deployments are addressed
        # - openstack-helm-multinode-temp-ubuntu
        # - openstack-helm-multinode-temp-centos
        # - openstack-helm-multinode-temp-fedora
        # - openstack-helm-multinode-temp-tempest
        # - openstack-helm-armada-deploy
        # - openstack-helm-armada-update-uuid
        # - openstack-helm-armada-update-passwords
        # - openstack-helm-ironic-ubuntu
